"""empty message

Revision ID: 645f40eb27b3
Revises: 9759b068c273
Create Date: 2020-02-13 18:45:23.829573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645f40eb27b3'
down_revision = '9759b068c273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
